import { expect, test } from 'bun:test';
import { getSql } from '../src/lib/server/db';
import { pruneTransientRecords } from '../src/lib/server/storage/retention.server';
const run = process.env.COAST_DB_TEST === '1' ? test : test.skip;
run('retention expires bounded transient data while preserving redeemed codes and delivery evidence', async () => {
  const db = getSql(), user = crypto.randomUUID(), instance = crypto.randomUUID(), connection = crypto.randomUUID(), account = crypto.randomUUID(), work = crypto.randomUUID();
  await db`insert into users(id,username) values(${user},${'retention-'+user})`;
  await db`insert into works(id,category,kind) values(${work},'screen','movie')`;
  await db`insert into provider_instances(id,provider,name,base_url) values(${instance},'trakt','Fixture','https://fixture.invalid')`;
  await db`insert into sync_accounts(id,user_id,instance_id,provider,server_identity,external_user_id) values(${account},${user},${instance},'trakt','fixture','fixture')`;
  await db`insert into provider_connections(id,user_id,instance_id,status) values(${connection},${user},${instance},'connected')`;
  await db`insert into sessions(user_id,token_hash,expires_at) select ${user},'expired-'||n,now()-interval '1 day' from generate_series(1,501) n`;
  await db`insert into sessions(user_id,token_hash,expires_at) values(${user},'valid',now()+interval '1 day')`;
  await db`insert into registration_invites(token_hash,expires_at,used_at) values('old-unused',now()-interval '40 days',null),('redeemed',now()-interval '40 days',now()-interval '39 days'),('recent',now()-interval '2 days',null)`;
  for(const approved of [true,false]) await db`insert into collection_projection_previews(connection_id,account_id,configuration_version,configuration,snapshot,approved,created_at) values(${connection},${account},${crypto.randomUUID()},'{}'::jsonb,'{}'::jsonb,${approved},now()-interval '2 days')`;
  await db`insert into outbox_actions(user_id,connection_id,kind,payload,state,updated_at) values(${user},${connection},'trakt.collection-project',${{evidence:'retained'}},'succeeded',now()-interval '400 days')`;
  await db`insert into synced_rooms(host_id,media_id,media_type,duration_seconds,created_at,ended_at) values(${user},${work},'video',100,now()-interval '2 days',null),(${user},${work},'video',100,now()-interval '10 days',now()-interval '8 days')`;
  const result = await pruneTransientRecords();
  expect(result.busy).toBe(false); expect(result.expired).toBe(1);
  expect((await db`select count(*)::int as n from sessions where token_hash like 'expired-%'`)[0].n).toBe(1);
  expect((await db`select token_hash from sessions where token_hash='valid'`)).toHaveLength(1);
  expect((await db`select token_hash from registration_invites order by token_hash`).map((r: {token_hash:string})=>r.token_hash)).toEqual(['recent','redeemed']);
  expect(await db`select id from collection_projection_previews where approved`).toHaveLength(1);
  expect(await db`select id from collection_projection_previews where not approved`).toHaveLength(0);
  expect(await db`select id from outbox_actions where state='succeeded'`).toHaveLength(1);
  expect(await db`select id from synced_rooms where ended_at is not null`).toHaveLength(1);
  await pruneTransientRecords();
  expect(await db`select id from sessions where token_hash like 'expired-%'`).toHaveLength(0);
});
